In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')

In [ ]:
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
dataset.shape

(150, 5)

In [ ]:
X = dataset.iloc[:,:4].values

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y = dataset['species'].values
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 0.19406156, -0.82722623,  0.78087748,  0.54778974],
       [-1.1195859 , -0.15950999, -1.29274453, -1.27095881],
       [ 2.22424398, -0.60465415,  1.67757888,  1.06743219],
       [ 1.14944152, -0.15950999,  1.00505283,  1.1973428 ],
       [-0.52247342,  1.39849456, -1.23670069, -1.27095881],
       [-0.40305092, -1.49494246,  0.05230758, -0.10176331],
       [-0.88074091,  0.9533504 , -1.29274453, -1.1410482 ],
       [-0.76131841,  2.28878288, -1.23670069, -1.40086942],
       [ 1.03001903,  0.50820625,  1.1171405 ,  1.1973428 ],
       [ 0.67175154, -0.38208207,  0.33252677,  0.15805791],
       [ 1.03001903, -0.15950999,  0.83692131,  1.45716402],
       [-0.52247342,  0.73077833, -1.23670069, -1.01113759],
       [-0.28362843, -0.38208207, -0.05978009,  0.15805791],
       [-0.04478344,  2.0662108 , -1.4048322 , -1.27095881],
       [-0.28362843, -0.15950999,  0.2204391 ,  0.15805791],
       [-1.0001634 ,  0.9533504 , -1.18065685, -0.75131637],
       [ 0.07463906,  0.

In [ ]:
X_test

array([[-1.47785339,  0.28563417, -1.29274453, -1.27095881],
       [-1.23900839, -0.15950999, -1.29274453, -1.1410482 ],
       [ 0.55232904, -1.27237038,  0.72483364,  0.93752157],
       [ 0.07463906, -0.15950999,  0.78087748,  0.80761096],
       [-1.71669838, -0.15950999, -1.34878837, -1.27095881],
       [-1.1195859 ,  0.06306209, -1.23670069, -1.40086942],
       [ 1.26886402,  0.06306209,  0.78087748,  1.45716402],
       [-0.76131841,  0.9533504 , -1.23670069, -1.27095881],
       [ 0.07463906, -0.15950999,  0.27648293,  0.41787913],
       [-0.28362843, -1.27237038,  0.10835142, -0.10176331],
       [-0.52247342,  0.73077833, -1.12461301, -1.27095881],
       [-0.40305092, -1.04979831,  0.38857061,  0.0281473 ],
       [ 0.31348405, -0.60465415,  0.16439526,  0.15805791],
       [ 0.67175154, -0.82722623,  0.89296515,  0.93752157],
       [ 0.79117403, -0.15950999,  1.00505283,  0.80761096],
       [ 0.43290655, -0.38208207,  0.33252677,  0.15805791],
       [ 0.67175154,  0.

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array(['setosa', 'setosa', 'virginica', 'virginica', 'setosa', 'setosa',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'virginica', 'virginica',
       'setosa', 'virginica', 'versicolor', 'versicolor'], dtype='<U10')

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 8,  0,  0],
       [ 0, 10,  0],
       [ 0,  1, 11]])

In [ ]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))


Accuracy :  0.9666666666666667


In [ ]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0       setosa           setosa
1       setosa           setosa
2    virginica        virginica
3    virginica        virginica
4       setosa           setosa
5       setosa           setosa
6    virginica        virginica
7       setosa           setosa
8   versicolor       versicolor
9   versicolor       versicolor
10      setosa           setosa
11  versicolor       versicolor
12  versicolor       versicolor
13   virginica        virginica
14   virginica        virginica
15  versicolor       versicolor
16   virginica        virginica
17  versicolor       versicolor
18   virginica        virginica
19  versicolor       versicolor
20   virginica       versicolor
21   virginica        virginica
22  versicolor       versicolor
23      setosa           setosa
24   virginica        virginica
25   virginica        virginica
26      setosa           setosa
27   virginica        virginica
28  versicolor       versicolor
29  versicolor       versicolor